export const surpriseMePrompts = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "A futuristic cityscape at night",
  "An otherworldly forest with glowing mushrooms",
  "A steampunk airship flying through the clouds",
  "A surreal underwater world with bioluminescent creatures",
  "A post-apocalyptic wasteland with a lone survivor",
  "A magical garden with talking flowers",
  "A cyberpunk street with neon lights and flying cars",
  "A desert landscape with a towering sandstorm",
  "An alien planet with strange landscapes and creatures",
  "A haunted castle on a misty hill",
  "A mythical creature like a unicorn or dragon",
  "A time traveler exploring different eras",
  "A robot factory with assembly lines and conveyor belts",
  "A dreamlike landscape with floating islands",
  "A retro-futuristic space station",
  "A fantastical castle with turrets and battlements",
  "A deep space probe exploring the galaxy",
  "A forest clearing with a mysterious portal",
  "A futuristic laboratory with advanced technology",
  "A giant sea monster attacking a ship",
  "An abandoned city with overgrown vegetation",
  "A space battle between starships",
  "A snow-covered landscape with a frozen river",
  "A fantasy tavern filled with magical patrons",
  "A giant tree with a hidden village in its branches",
  "A futuristic megalopolis with towering skyscrapers",
  "A pirate ship sailing the high seas",
  "A serene mountain lake with a hidden cave",
  "A city street in a cyberpunk dystopia",
  "A lost temple hidden deep in the jungle",
  "A space explorer encountering an alien civilization",
  "A giant robot battling a monster in a city",
  "A serene beach with crystal-clear waters",
  "A mystical library with ancient books and artifacts",
  "A space elevator connecting Earth to orbit",
  "A medieval castle under siege",
  "A cybernetic organism with human and robotic parts",
  "A dark forest with twisted trees and eerie sounds",
  "A futuristic sports arena with advanced technology",
  "A secret underground laboratory",
  "A mystical island with ancient ruins",
  "A space station orbiting a gas giant",
  "A steampunk train traveling through a mountain pass",
  "A time machine journeying through different eras",
  "A mythical creature like a griffin or phoenix",
  "A city skyline with towering skyscrapers",
  "A futuristic hovercraft speeding through a canyon",
  "A portal to a parallel universe",
  "A haunted mansion with creepy decor",
  "A spaceship exploring the outer reaches of the galaxy",
  "A vast desert with sand dunes and rocky outcrops",
  "A magical castle in the clouds",
  "A futuristic vehicle racing through a city",
  "A giant spider attacking a town",
  "A snow-covered village with a cozy atmosphere",
  "A futuristic city with flying cars and advanced technology",
  "A mythical creature like a centaur or minotaur",
  "A mysterious cave with glowing crystals",
  "A post-apocalyptic city with ruins and debris",
  "A space colony on a distant planet",
  "A castle on a rocky cliff overlooking the sea",
  "A cyborg warrior battling an alien invasion",
  "A dark and twisted labyrinth",
  "A futuristic spaceship exploring deep space",
  "A fantasy marketplace with exotic goods and creatures",
  "A secret underground city",
  "A mystical forest with ancient ruins",
  "A space station orbiting a distant planet",
  "A steampunk airship docked at a floating city",
];
